### PR TITLE
replay in chunks (backport)

### PR DESCRIPTION
**Pull request by prolic**
resolves: https://github.com/prooph/event-store-doctrine-adapter/issues/35

backport of https://github.com/prooph/event-store-doctrine-adapter/pull/40 (Support for PHP 7.1)

### CODE REVIEW

**Comment by prolic** [comment]
@basz Can you test this branch with your memory limit problems?

**Comment by prolic** [comment]
Question: is 100 a good chunk size or should it be increased?

**Comment by basz** [comment]
want to test, but am still stuck at php7.0.

Regarding the chuck size. 100 feels a bit small to me. I guess it depends on the size of the events, but 5000 seems a better number... say each event is 10Kb then 5Mb memory usage is ok... If your events are ~1Mb then even a chuck size of 100 would amount to 100Mb footprint. Once I have this running I'll do some tests to see how a smaller chunk size decreases performance.

**Comment by prolic** [comment]
I tests myself with a stream of 100.000 events. Here are my results:

REPLAY: 100.000 events

chunk size: none
memory limit: 66723840
time used: 3.5s

chunk size: 100
memory limit: 4194304
time used: 8m 29s

chunk size: 1000
memory limit: 4194304
time used: 53.9s

chunk size: 5000
memory limit: 10485760
time used: 13.6s

chunk size: 10000
memory limit: 16777216
time used: 8.5s

The memory limit used depends to the size of the average event of course, but I think when someone handles events in megabyte-size, he has to use also a lot of memory for replaying, so I wouldn't worry too much about it.

So which number to chose? @basz @codeliner

**Comment by basz** [comment]
wow, such a slowdown...
```
with a chunk size of 100; ~190x slower for 1000 additional queries...
with a chunk size of 1000; ~15x slower for 100 additional queries...
with a chunk size of 5000; ~4x slower for  20 additional queries...
```

I guest I would start by using a chuck size of 100000. IMO for a replay some memory should be assumed to be available and speed should be favoured over memory.

ps. this not something which can be made configurable?
ps. now i see this is a back port! I shall test...

**Comment by prolic** [comment]
Yes this can be made configurable. I also think 10.000 is a better size. Let's go with that and make it the default. Configuration option will be added later this evening.

**Comment by basz** [comment]
works for me! thank you

**Comment by codeliner** [comment]
looks good :+1:

**Pull request merged**
