### PR TITLE
optimize database scheme

### PR DESCRIPTION
**Pull request by sandrokeil**
This uses the most optimized available type of the column.

Has the DateTime ISO8601 + microseconds UTC format always a **length of 26** or why was it 50? The `aggregate_id` length was also set to 36 (UUID4).

Note: I think there is no major release necessary. Because columns are the same and nothing happens if the migration already exists.

### CODE REVIEW

**Comment by prolic** [comment]
looks good, but we shouln't limit the aggregate_type to 100 chars, FQCN can be longer than that.

**Comment by sandrokeil** [comment]
@prolic What do you think is a good length for the aggregate_type column? 255? We have to ensure it's the same length in the [snapshot table](https://github.com/prooph/snapshot-doctrine-adapter/pull/14).

**Comment by prolic** [comment]
Good question. Ideally I would not limit the class name length to anything. The longest class name I could find is: "aspectj.weaver.patterns.HasThisTypePatternTriedToSneakInSomeGenericOrParameterizedTypePatternMatchingStuffAnywhereVisitor" - 120 chars. The class name is REALLY long, but I could imagine longer namespace names, the longest namespace name I have in my current project is 45 chars. Combined with the other names, that would make 142.

Anyway, if we really need to limit the class name to something, we need to document that and also provide a path what to do, when your class name exceeds that specific limit, as this could lead to the false aggregate being loading from the event store.

**Comment by sandrokeil** [comment]
@prolic The length is only relevant for the index in the snapshot table and it's only a suggestion. People can change it. However, a solid length should be applied. /cc @codeliner

**Comment by codeliner** [comment]
scheme optimizations look good.
I agree that 100 chars for the aggregate_type are maybe not enough. However, like mentioned by @sandrokeil it is a suggestion. Should we increase the value to 150 chars and add a note in the docs that this setting needs to be aligned if longer FQCN is possible?

**Comment by prolic** [comment]
@codeliner yes, let's add some docs for it.

**Comment by codeliner** [comment]
k, @sandrokeil can you add the note with your PR?

**Comment by sandrokeil** [comment]
@codeliner I've updated the length to 150 chars and added a note in the readme.

**Comment by prolic** [comment]
There were 2 failures:

1) ProophTest\EventStore\Adapter\Doctrine\Schema\EventStoreSchemaTest::it_creates_a_single_stream_schema_correctly

Failed asserting that 150 matches expected 100.

/home/travis/build/prooph/event-store-doctrine-adapter/tests/Schema/EventStoreSchemaTest.php:66

2) ProophTest\EventStore\Adapter\Doctrine\Schema\EventStoreSchemaTest::it_creates_a_aggregate_type_stream_schema_correctly

Failed asserting that 150 matches expected 100.

**Comment by sandrokeil** [comment]
I fixed it. I think there is more optimization potential depending on the executed queries. I will check this.

**Pull request merged**
